/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#warning "Secure / Non-Secure regions are not initialized. Please add code to properly initialize the Secure / Non-secure regions. This can be ignored if you know what you are doing."


int main(void)
{
	/**
	 * Add code here for initializing the non-secure stack pointer
	 * and then perform the jump to the non-secure reset handler
	 */

    /* Loop forever */
	for(;;);
}

/**
 * This function is Secure and is call-able from Non-Secure regions.
 */
__attribute__((cmse_nonsecure_entry)) int secure_add_one(int value) {
	return value + 1;
}
